// @ts-nocheck -- bewusst JS-kompatibel, damit die bestehenden isolierten QA-Loader die Datei direkt laden koennen.

const UI_TEXT = Object.freeze({
  de: Object.freeze({
    offline: "OFFLINE",
    no_bus: "NICHT IM BUS",
    no_data: "KEINE DATEN",
    bus_loading: "BUS WIRD GELADEN",
    map_loading: "KARTE LÄDT",
    no_route: "KEINE ROUTE",
    stale_route: "ROUTE ALT",
    off_route: "ABSEITS ROUTE",
    reversing: "RÜCKWÄRTS",
    live: "LIVE",
    unknown: "UNBEKANNT",
    early: "VERFRÜHT",
    late: "VERSPÄTET",
    punctual: "PÜNKTLICH",
    no_stop: "-- KEINE HALTESTELLE --",
    no_mission: "-- KEINE MISSION --",
    lowering: "SENKT AB",
    raising: "HEBT AN",
    active: "AKTIV",
    ready: "READY",
    on: "AN",
    enabled: "EIN",
    off: "AUS",
    open: "OFFEN",
    closed: "ZU",
    next_stop: "NÄCHSTE HALTESTELLE",
    next_stop_short: "NÄCHSTER HALT",
    terminal_pause: "PAUSENPUNKT",
    destination: "ENDHALT",
    stop_request: "HALTEWUNSCH",
    arrival: "ANKUNFT",
    arrival_short: "ANK",
    departure: "ABFAHRT",
    departure_short: "ABF",
    deviation: "ABWEICHUNG",
    ingame_time: "INGAME ZEIT",
    status: "STATUS",
    vehicle: "FAHRZEUG",
    live_telemetry: "LIVE-TELEMETRIE",
    speed_limit: "STRECKENLIMIT",
    gear: "GANG",
    battery: "AKKU",
    doors: "TÜREN",
    parking_brake: "FESTSTELLBREMSE",
    kneeling: "KNEELING",
    power: "LEISTUNG",
    average_consumption: "Ø VERBRAUCH",
    remaining: "REST",
    progress: "FORTSCHRITT",
    prediction: "PROGNOSE",
    game_disconnected: "SPIEL / TELEMETRIE NICHT VERBUNDEN",
    fullpanel: "FULLPANEL",
    occupy_all_encoders: "ALLE 4 ENCODER BELEGEN",
    segment: "SEGMENT",
    detected: "ERKANNT",
    navigation: "NAVIGATION",
    straight: "GERADEAUS",
    slight_left: "LEICHT LINKS",
    left: "LINKS",
    sharp_left: "SCHARF LINKS",
    slight_right: "LEICHT RECHTS",
    right: "RECHTS",
    sharp_right: "SCHARF RECHTS",
    lane_left: "SPUR LINKS",
    lane_right: "SPUR RECHTS",
    uturn: "WENDEN",
    stop: "HALTESTELLE",
    pause: "PAUSE",
    recalculating: "BERECHNUNG",
    maneuver: "MANÖVER",
    route_length: "LINIENLÄNGE",
    remaining_distance: "RESTSTRECKE",
    route_progress: "LINIENFORTSCHRITT",
    estimated_arrival: "GESCHÄTZTE ANKUNFT",
    predicted_delta: "PROGNOSE-DELTA",
    prediction_confidence: "PROGNOSESICHERHEIT",
    high: "HOCH",
    medium: "MITTEL",
    low: "NIEDRIG",
    not_available: "NICHT VERFÜGBAR",
    display_only: "NUR ANZEIGE",
    toggle: "UMSCHALTEN",
    rotate: "DREHREGLER",
    slower_faster: "LANGSAMER / SCHNELLER",
    left_right: "LINKS / RECHTS",
    telemetry_disconnected: "TELEMETRIE GETRENNT",
    climate: "KLIMA",
    temperature: "TEMPERATUR",
    fan: "LÜFTER",
    fan_speed: "LÜFTERGESCHWINDIGKEIT",
    ventilation_auto: "LÜFTER AUTOMATIK",
    airflow: "LUFTVERTEILUNG",
    heating_cooling: "HEIZEN / KÜHLEN",
    cooling: "KÜHLEN",
    heating: "HEIZEN",
    rear_climate: "KLIMA HINTEN",
    front_circulation: "UMLUFT VORNE",
    circulation: "UMLUFT",
    higher: "HÖHER",
    lower: "TIEFER",
    stage: "STUFE",
    stage_higher: "STUFE HÖHER",
    stage_lower: "STUFE NIEDRIGER",
    position_higher: "POSITION HÖHER",
    position_lower: "POSITION NIEDRIGER",
    target: "ZIEL",
    hold: "HALTEN",
    top: "OBEN",
    bottom: "UNTEN",
    retarder_off: "RETARDER AUS",
    vehicle_function: "FAHRZEUGFUNKTION",
    light_switch: "LICHTSCHALTER",
    daytime_lights: "TAGFAHRLICHT",
    parking_lights: "STANDLICHT",
    headlights: "ABBLENDLICHT",
    high_beam: "FERNLICHT",
    front_fog: "NEBEL VORNE",
    rear_fog: "NEBEL HINTEN",
    onboard_computer_select: "BORDCOMPUTER ATRON AUSWÄHLEN",
    accept: "ANNEHMEN",
    cash: "BARGELD",
    real_event: "ECHTES EVENT",
    atron_coin: "ATRON MÜNZE",
    timetable: "FAHRPLAN",
    only_display: "Nur Anzeige",
    change_dashboard: "Dashboard wechseln",
    layer: "LAYER",
    sun_blind: "SONNENBLENDE",
    windshield_wiper: "SCHEIBENWISCHER",
    parking_short: "STAND",
    headlights_short: "ABBLEND",
    front_fog_short: "NEBEL V",
    rear_fog_short: "NEBEL H",
    move_down: "herunterfahren",
    move_up: "hochfahren",
    buffer_60s: "60 S PUFFER",
    please_wait: "BITTE WARTEN",
    saved_upper: "GESPEICHERT",
    error: "FEHLER",
    no_function: "Keine Funktion",
    climate_control_turn: "Klima-Regler drehen",
    saved: "Gespeichert",
    function: "Funktion",
    display: "Anzeige",
  }),
  en: Object.freeze({
    offline: "OFFLINE",
    no_bus: "NOT IN BUS",
    no_data: "NO DATA",
    bus_loading: "BUS LOADING",
    map_loading: "MAP LOADING",
    no_route: "NO ROUTE",
    stale_route: "ROUTE STALE",
    off_route: "OFF ROUTE",
    reversing: "REVERSING",
    live: "LIVE",
    unknown: "UNKNOWN",
    early: "EARLY",
    late: "LATE",
    punctual: "ON TIME",
    no_stop: "-- NO STOP --",
    no_mission: "-- NO MISSION --",
    lowering: "LOWERING",
    raising: "RAISING",
    active: "ACTIVE",
    ready: "READY",
    on: "ON",
    enabled: "ON",
    off: "OFF",
    open: "OPEN",
    closed: "CLOSED",
    next_stop: "NEXT STOP",
    next_stop_short: "NEXT STOP",
    terminal_pause: "TERMINAL BREAK",
    destination: "TERMINUS",
    stop_request: "STOP REQUEST",
    arrival: "ARRIVAL",
    arrival_short: "ARR",
    departure: "DEPARTURE",
    departure_short: "DEP",
    deviation: "DEVIATION",
    ingame_time: "IN-GAME TIME",
    status: "STATUS",
    vehicle: "VEHICLE",
    live_telemetry: "LIVE TELEMETRY",
    speed_limit: "SPEED LIMIT",
    gear: "GEAR",
    battery: "BATTERY",
    doors: "DOORS",
    parking_brake: "PARKING BRAKE",
    kneeling: "KNEELING",
    power: "POWER",
    average_consumption: "Ø CONSUMPTION",
    remaining: "REMAINING",
    progress: "PROGRESS",
    prediction: "PREDICTION",
    game_disconnected: "GAME / TELEMETRY DISCONNECTED",
    fullpanel: "FULLPANEL",
    occupy_all_encoders: "ASSIGN ALL 4 ENCODERS",
    segment: "SEGMENT",
    detected: "DETECTED",
    navigation: "NAVIGATION",
    straight: "STRAIGHT",
    slight_left: "SLIGHT LEFT",
    left: "LEFT",
    sharp_left: "SHARP LEFT",
    slight_right: "SLIGHT RIGHT",
    right: "RIGHT",
    sharp_right: "SHARP RIGHT",
    lane_left: "KEEP LEFT",
    lane_right: "KEEP RIGHT",
    uturn: "U-TURN",
    stop: "BUS STOP",
    pause: "BREAK",
    recalculating: "RECALCULATING",
    maneuver: "MANEUVER",
    route_length: "ROUTE LENGTH",
    remaining_distance: "REMAINING DISTANCE",
    route_progress: "ROUTE PROGRESS",
    estimated_arrival: "ESTIMATED ARRIVAL",
    predicted_delta: "PREDICTED DELTA",
    prediction_confidence: "PREDICTION CONFIDENCE",
    high: "HIGH",
    medium: "MEDIUM",
    low: "LOW",
    not_available: "NOT AVAILABLE",
    display_only: "DISPLAY ONLY",
    toggle: "TOGGLE",
    rotate: "TURN",
    slower_faster: "SLOWER / FASTER",
    left_right: "LEFT / RIGHT",
    telemetry_disconnected: "TELEMETRY DISCONNECTED",
    climate: "CLIMATE",
    temperature: "TEMPERATURE",
    fan: "FAN",
    fan_speed: "FAN SPEED",
    ventilation_auto: "AUTO FAN",
    airflow: "AIRFLOW",
    heating_cooling: "HEATING / COOLING",
    cooling: "COOLING",
    heating: "HEATING",
    rear_climate: "REAR CLIMATE",
    front_circulation: "FRONT RECIRCULATION",
    circulation: "RECIRCULATION",
    higher: "HIGHER",
    lower: "LOWER",
    stage: "LEVEL",
    stage_higher: "LEVEL UP",
    stage_lower: "LEVEL DOWN",
    position_higher: "POSITION UP",
    position_lower: "POSITION DOWN",
    target: "TARGET",
    hold: "HOLD",
    top: "UP",
    bottom: "DOWN",
    retarder_off: "RETARDER OFF",
    vehicle_function: "VEHICLE FUNCTION",
    light_switch: "LIGHT SWITCH",
    daytime_lights: "DAYTIME LIGHTS",
    parking_lights: "PARKING LIGHTS",
    headlights: "HEADLIGHTS",
    high_beam: "HIGH BEAM",
    front_fog: "FRONT FOG",
    rear_fog: "REAR FOG",
    onboard_computer_select: "SELECT ATRON COMPUTER",
    accept: "ACCEPT",
    cash: "CASH",
    real_event: "REAL EVENT",
    atron_coin: "ATRON COIN",
    timetable: "TIMETABLE",
    only_display: "Display only",
    change_dashboard: "Change dashboard",
    layer: "LAYER",
    sun_blind: "SUN BLIND",
    windshield_wiper: "WINDSHIELD WIPER",
    parking_short: "PARKING",
    headlights_short: "LOW BEAM",
    front_fog_short: "FRONT FOG",
    rear_fog_short: "REAR FOG",
    move_down: "move down",
    move_up: "move up",
    buffer_60s: "60 S BUFFER",
    please_wait: "PLEASE WAIT",
    saved_upper: "SAVED",
    error: "ERROR",
    no_function: "No function",
    climate_control_turn: "Turn climate dial",
    saved: "Saved",
    function: "Function",
    display: "Display",
  }),
});

let displayLanguage = "de";

export function normalizeDisplayLanguage(value) {
  return String(value ?? "").toLowerCase().startsWith("en") ? "en" : "de";
}

export function setDisplayLanguage(value) {
  displayLanguage = normalizeDisplayLanguage(value);
  return displayLanguage;
}

export function getDisplayLanguage() {
  return displayLanguage;
}

export function translateUi(key, language = displayLanguage) {
  const normalized = normalizeDisplayLanguage(language);
  return UI_TEXT[normalized][key] ?? UI_TEXT.de[key] ?? String(key);
}

export function formatUiDecimal(value, digits = 1, language = displayLanguage) {
  const number = Number(value);
  if (!Number.isFinite(number)) return "--";
  const fixed = number.toFixed(digits);
  return normalizeDisplayLanguage(language) === "de"
    ? fixed.replace(".", ",")
    : fixed;
}
